"""initial schema

Revision ID: 2b83a004abca
Revises: 
Create Date: 2026-05-10 18:00:31.027664

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b83a004abca'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('window', sa.String(length=10), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('region', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('muted_until', sa.DateTime(), nullable=True),
    sa.Column('added_at', sa.DateTime(), nullable=False),
    sa.Column('last_msg_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('tg_message_id', sa.BigInteger(), nullable=False),
    sa.Column('author_tg_id', sa.BigInteger(), nullable=True),
    sa.Column('author_username', sa.String(length=255), nullable=True),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('posted_at', sa.DateTime(), nullable=False),
    sa.Column('analyzed_at', sa.DateTime(), nullable=True),
    sa.Column('is_lead', sa.Boolean(), nullable=True),
    sa.Column('project_type', sa.String(length=50), nullable=True),
    sa.Column('budget_usd', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('client_country', sa.String(length=20), nullable=True),
    sa.Column('urgency', sa.String(length=20), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'tg_message_id', name='uq_lead_source_msg')
    )
    op.create_index('ix_leads_status_posted', 'leads', ['status', 'posted_at'], unique=False)
    op.create_table('responses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('template_id', sa.Integer(), nullable=True),
    sa.Column('draft_text', sa.Text(), nullable=False),
    sa.Column('final_text', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('sent_to', sa.String(length=10), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('client_replied', sa.Boolean(), nullable=False),
    sa.Column('client_status', sa.String(length=20), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_responses_status_sent', 'responses', ['status', 'sent_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_responses_status_sent', table_name='responses')
    op.drop_table('responses')
    op.drop_index('ix_leads_status_posted', table_name='leads')
    op.drop_table('leads')
    op.drop_table('sources')
    op.drop_table('rate_limits')
    # ### end Alembic commands ###
