"""iter2 botstate quiet_hours_override

Revision ID: 58c74c504369
Revises: ba4da7a2b056
Create Date: 2026-05-10 21:20:59.979597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58c74c504369'
down_revision: Union[str, None] = 'ba4da7a2b056'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bot_state', sa.Column('quiet_hours_override', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('bot_state', 'quiet_hours_override')
    # ### end Alembic commands ###
