"""iter4 smart templates discovery response indexes

Revision ID: 7cbb54cdc07b
Revises: 58c74c504369
Create Date: 2026-05-10 22:20:17.355845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cbb54cdc07b'
down_revision: Union[str, None] = '58c74c504369'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('discovery_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('member_count', sa.Integer(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('predicted_region', sa.String(length=20), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('matched_query', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tg_id', name='uq_discovery_tg_id')
    )
    op.create_index('ix_discovery_status_discovered', 'discovery_candidates', ['status', 'discovered_at'], unique=False)
    op.create_table('templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('variant', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('traffic_share', sa.Integer(), nullable=False),
    sa.Column('sent_count', sa.Integer(), nullable=False),
    sa.Column('reply_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('responses') as batch:
        batch.add_column(sa.Column('author_tg_id_cached', sa.BigInteger(), nullable=True))
        batch.add_column(sa.Column('client_replied_at', sa.DateTime(), nullable=True))
        batch.create_foreign_key(
            'fk_responses_template_id', 'templates', ['template_id'], ['id'],
        )
    op.create_index(
        'ix_responses_author_status_sent', 'responses',
        ['author_tg_id_cached', 'status', 'sent_at'], unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_index('ix_responses_author_status_sent', table_name='responses')
    with op.batch_alter_table('responses') as batch:
        batch.drop_constraint('fk_responses_template_id', type_='foreignkey')
        batch.drop_column('client_replied_at')
        batch.drop_column('author_tg_id_cached')
    op.drop_table('templates')
    op.drop_index('ix_discovery_status_discovered', table_name='discovery_candidates')
    op.drop_table('discovery_candidates')
    # ### end Alembic commands ###
