"""iter2 bot_state table

Revision ID: ba4da7a2b056
Revises: 2b83a004abca
Create Date: 2026-05-10 21:19:01.240074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba4da7a2b056'
down_revision: Union[str, None] = '2b83a004abca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bot_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('last_digest_at', sa.DateTime(), nullable=True),
    sa.Column('last_health_ok_at', sa.DateTime(), nullable=True),
    sa.Column('consecutive_health_fails', sa.Integer(), nullable=False),
    sa.Column('last_rate_limit_rotation_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bot_state')
    # ### end Alembic commands ###
